name: uep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  intl_phone_number_input: ^0.7.4
  pinput: ^5.0.0
  smart_auth: ^2.0.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.6.0
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  path: ^1.9.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter_facebook_auth: ^7.1.0
  # flutter_appauth: ^7.0.0
  # flutter_web_auth: ^0.5.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/icons/