// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT1EXaK_YorK7wf5hwEdfZ6POY_UhOCzk',
    appId: '1:1086022332299:web:6c8151b4686080c2f0898e',
    messagingSenderId: '1086022332299',
    projectId: 'millima-36de9',
    authDomain: 'millima-36de9.firebaseapp.com',
    storageBucket: 'millima-36de9.appspot.com',
    measurementId: 'G-G9C87SX4QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnwET3eT-vgdpdPKApHSHw4MlGChRUb4o',
    appId: '1:1086022332299:android:aa83fe6e9658689bf0898e',
    messagingSenderId: '1086022332299',
    projectId: 'millima-36de9',
    storageBucket: 'millima-36de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIPcU-j011SzrP17YIoklGjFokCbZxGi8',
    appId: '1:1086022332299:ios:5bfbc6ee39be5c53f0898e',
    messagingSenderId: '1086022332299',
    projectId: 'millima-36de9',
    storageBucket: 'millima-36de9.appspot.com',
    androidClientId: '1086022332299-c684vqsf9kue6lb9hu5qmou6aq5hb766.apps.googleusercontent.com',
    iosClientId: '1086022332299-l9q7t9nl66eb21dgd1nlhmra6mm96ell.apps.googleusercontent.com',
    iosBundleId: 'com.example.uep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIPcU-j011SzrP17YIoklGjFokCbZxGi8',
    appId: '1:1086022332299:ios:5bfbc6ee39be5c53f0898e',
    messagingSenderId: '1086022332299',
    projectId: 'millima-36de9',
    storageBucket: 'millima-36de9.appspot.com',
    androidClientId: '1086022332299-c684vqsf9kue6lb9hu5qmou6aq5hb766.apps.googleusercontent.com',
    iosClientId: '1086022332299-l9q7t9nl66eb21dgd1nlhmra6mm96ell.apps.googleusercontent.com',
    iosBundleId: 'com.example.uep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT1EXaK_YorK7wf5hwEdfZ6POY_UhOCzk',
    appId: '1:1086022332299:web:8b10ce718181cf81f0898e',
    messagingSenderId: '1086022332299',
    projectId: 'millima-36de9',
    authDomain: 'millima-36de9.firebaseapp.com',
    storageBucket: 'millima-36de9.appspot.com',
    measurementId: 'G-87Y5CQ4XMY',
  );
}
